### DISCUSSION TITLE
Performance compare between a separate group and a weight round-robin group

### DISCUSSION THREAD

**Discussion by northopn** [phstc/shoryuken#809] [Q&A]
I ran an experiment between these Shoryuken's configs with 3 queues/workers. 

### 1. Separate groups. 
```
# shoryuken.yml
delay: 0
groups:
  group1
    concurrency: 1
    queues:
    - queue1
  group2:
    concurrency: 1
    queues:
    - queue2
  group3:
    concurrency: 6
    queues:
    - queue2
``` 
```
# shoryuken.rb 
Shoryuken.sqs_client_receive_message_opts[:group1] = { wait_time_seconds: 20 }
Shoryuken.sqs_client_receive_message_opts[:group2] = { wait_time_seconds: 20 }
Shoryuken.sqs_client_receive_message_opts[:group3] = { wait_time_seconds: 20 }
```

### 2. WRR group
```
delay: 0 
concurrency: <%= ENV.fetch("SHORYUKEN_CONCURRENCY", 25).to_i %> 
groups:
  weighted_round_robin_group:
    polling_strategy: WeightedRoundRobin
    queues:
      - [queue1, 1]
      - [queue2, 5]
      - [queue3, 10]
```
```
Shoryuken.sqs_client_receive_message_opts[:weighted_round_robin_group] = { wait_time_seconds: 10 }
```

I ran K6 to test against both configs and I found an odd result. please check below. because in my mind I thought using a workers pool would give a better result.
K6 script scenario I used was publishing queue-message to all queues with ramping-up rate for 10mins.
```
{
  "discardResponseBodies": false,
  "scenarios": {
    "contacts": {
      "executor": "ramping-arrival-rate",
      "startRate": 1,
      "timeUnit": "1s",
      "preAllocatedVUs": 1,
      "maxVUs": 1000,
      "stages": [{ "target": 40, "duration": "600s" }]
    }
  }
}
```

Here are the results
1. Separate group 
![Screenshot 2568-02-14 at 23 37 17](https://github.com/user-attachments/assets/a563a448-c6fc-4f37-a9a8-4640fe976c28)
with this config, the consumer processes the messages almost instantly once the message is landed on the queue. and the oldest message's average time is 30 seconds

2. WRR 
![Screenshot 2568-02-14 at 23 37 44](https://github.com/user-attachments/assets/da8bbb9c-fb1e-46ea-9fef-7eb5eeeb1dd8)
with this config, I spent almost 40mins to finish up. and the oldest message in the queue was an hour. 

The worker code
```
class Queue2Worker
  include Shoryuken::Worker

  shoryuken_options queue: "queue2", auto_delete: true, body_parser: :json

  def perform(sqs_msg, body)
    # Queue's logic
  end
end

```

please give me advice. I can provide more info if needed
