### ISSUE TITLE
:region option not passed to AWS client?

### ISSUE THREAD

**Issue by vemv** [phstc/shoryuken#180]
Hey there!

Despite I set `region: foo` in my shoryuken.yml, this option doesn't always get passed to the AWS client, as I understand it. The AWS_REGION env var is attempted to be read instead.

**Background**

I recently decided to leave AWS_REGION unset. That's what triggered the error. But no errors should happen, given that I already explicitly set the region in shoryuken.yml

**Backtrace**

https://gist.github.com/vemv/7a61fb5959e91abede46

**Workaround**

Create a Rails initializer with:

`Aws.config[:region] = 'foo'`

**Comment by phstc** [comment]
Hi @vemv 

Could you share your `shoryuken.yml`? Are you defining `sqs_endpoint`?

[Here](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/environment_loader.rb#L75) Shoryuken sets the `region` passed in `aws`, as suggested on the [docs](https://github.com/aws/aws-sdk-ruby#configuration-options).

Probably the issue is [here](https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/client.rb#L20), probably not counting on the `region` set through the `environment_loader`.

**Comment by vemv** [comment]
My shoryuken.yml looks like this:

```
aws:
  region: <%= a_method_that_returns_a_region_string %>
  receive_message: # See http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#receive_message-instance_method
    attribute_names:
      - All
concurrency: 4
delay: 0
queues:
  - [mailers, 1]
```

I'm 100% positive that `a_method_that_returns_a_region_string` does not ever return nil at any point of the Rails initialization process.

If you create a branch patching the suspect (https://github.com/phstc/shoryuken/blob/master/lib/shoryuken/client.rb#L20) I can try it immediately and tell you if that worked.

Cheers - Victor
