### ISSUE TITLE
Per-queue receive_message parameter specification

### ISSUE THREAD

**Issue by cjlarose** [phstc/shoryuken#265]
I'm interested in being able to specify different options for the calls to `receive_message`, but on a per-queue basis. Right now, it seems possible to define those options globally, but it would be very useful for me to be able to, for example, set the `visibility_timeout` on the `receive_message` calls to a different value depending on the queue.

Currently, you can set the `wait_time_seconds` for all `receive_message` calls to the same value:

```yaml
aws:
  access_key_id:      ...       # or <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key:  ...       # or <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region:             us-east-1 # or <%= ENV['AWS_REGION'] %>
  receive_message:
    wait_time_seconds: 90
queues:
  - [high_priority, 6]
  - [default, 2]
  - [low_priority, 1]
```

Here's an example of what per-queue `receive_message` configuration might look like. Adding anything additional to the `queues` arrays might look awkward, so a new queue configuration format using hashes might be more appropriate:

```yaml
aws:
  access_key_id:      ...       # or <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key:  ...       # or <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region:             us-east-1 # or <%= ENV['AWS_REGION'] %>
  receive_message:
    wait_time_seconds: 90
queues:
  high_priority:
    weight: 6
    receive_message:
      wait_time_seconds: 30
  default:
    weight: 2
    receive_message:
      visibility_timeout: 10
  low_priority:
    weight: 1
    receive_message:
      visibility_timeout: 45
```

I think these changes can be made in a backward-compatible way and that the behavior of specifying global receive_message options which can be overridden on a per-queue basis is natural. Would a pull request with these changes be welcome?
