### ISSUE TITLE
Support concurrency per queue

### ISSUE THREAD

**Issue by phstc** [phstc/shoryuken#347]
Would be cool to be able to set concurrency per queue. Sometimes due some API limits there are some queues we can't process at full speed, but we don't want to limit down the entire concurrency, so it would be great to set concurrency on a queue basis.

See #337

**Comment by elsurudo** [comment]
I was just going to post the same thing.

Last night my system basically ran into a deadlock because it was trying to process too many large images at once, and Heroku was killing it for memory usage reasons.

For now I just need to reduce the concurrency, but it's not a good solution because I have lots of other lightweight jobs which can be run in the meantime, but I'd like to (for example) limit my image processing worker to a concurrency of 3.

Any ideas on strategy with this? I see on the attached ticket that custom polling strategies are implemented, but not documented?

**Comment by phstc** [comment]
Hi @elsurudo 

Not documented yet, I still need to work on that.

So I was thinking on something like:

```yaml
concurrency: 25

queues:
  - [queue3, 1, 3]
  - [queue20, 2, 20]
  - [queue-default, 3]
```

If the concurrency isn't supplied, it would fallback to the original global one `concurrency`.  That config means, the total Shoryuken concurrency is 25, but `queue3` uses 3, `queue-default` can use 25 processors etc, so basically the concurrency set per queue would be just a subset of the total available concurrency.

For controlling the concurrency per queue I was thinking on using one [`AtomicFixnum`](www.rubydoc.info/github/ruby-concurrency/concurrent-ruby/Concurrent/AtomicFixnum) per queue.

What do you think?

**Comment by elsurudo** [comment]
@phstc I like that way of configuring it – should work well IMO. Using the `AtomicFixnum` for synchronization between the threads makes sense, too.

**Comment by phstc** [comment]
Hi @elsurudo 

After a lot of thought on it, I'm reconsidering the priority per queue in the way [I mentioned before](https://github.com/phstc/shoryuken/issues/347#issuecomment-290517847):


```yaml
concurrency: 25

queues:
  - [queue1, 10, 3] # priority: 10, concurrency: 3
  - [queue2, 5, 10] # priority: 5, concurrency: 10
```

Due to the current implementation of Shoryuken, this can get very complex. Also the priority gets confusing like `queue1` has 10, but since it has concurrency 3, it's hard to guarantee the sequential priority given that `queue2` has concurrency 10. I did a PoC #390 for this impl, the code is a bit messy, but it's working.

Another solution, which I'm kinda more excited about, is to allow creating groups in Shoryuken:

```yaml
concurrency: 25

queues:
  - [queue1, 10]
  - [queue2, 5]
  
groups:
  fifo:
    concurrency: 1
    queues:
      - [queue1.fifo, 10]
```

For compatibility purposes `queues` and `concurrency` would be automatically added to a group called `default` at runtime.

With that, a single Shoryuken process would run more than one set of queues and concurrencies isolated. This is very useful for FIFO Queues since you can't `concurrency > 1`, if you want to make sure messages within the same `group-id` are sequentially processed. 

Also, the fetcher is per group, so Shoryuken would be able to fetch in parallel. This can be an alternative for [StrictPriority](https://github.com/phstc/shoryuken/wiki/Polling-strategies#strictpriority).

PoC: #389

WDYT?

@waynerobinson @atyndall any thoughts?

**Comment by waynerobinson** [comment]
This sounds really good. We currently only use a single queue per shoryuken.yml to enable priority-based queueing because of the lack of a per-queue fetcher. 

This seems to do everything we would need, whilst having some extra functionality for others. 👍

**Comment by waynerobinson** [comment]
It would also be kind of nice to specify the group name in the Worker when setting which queue it uses rather than having to have the SQS queue names in an app-accessible environment variable somewhere too. :-)

**Comment by atyndall** [comment]
@phstc If I understand you correctly, would each of these groups be able to adopt its own polling strategy?

Right now due to the time each of our jobs take we would probably still need to use StrictPriority in our approach, but we could potentially gain throughput by redefining our jobs from;
```
queues:
 - [group_a_high_priority, 4]
 - [group_b_high_priority, 3]
 - [group_a_low_priority,  2]
 - [group_b_low_priority,  1]
```
to
```
groups:
  group_a:
    queues:
      - [group_a_high_priority, 2]
      - [group_a_low_priority,  1]
  group_b:
    queues:
      - [group_b_high_priority, 2]
      - [group_b_low_priority,  1]
``` 

if each group has its own independent StrictPriority it is observing.
