### ISSUE TITLE
shoryuken store data only to 'default' queue

### ISSUE THREAD

**Issue by likitung** [phstc/shoryuken#386]
Hello, shoryuken store all messages only to default queue instead of  queue called "development_reports", what I'm doing wrong? 

### Config

```yaml
concurrency: 2  # The number of allocated threads to process messages. Default 25
delay: 0         # The delay in seconds to pause empty queues. Default 0
queues:
  - "development_reports"
  - "development_default"
aws:
  access_key_id:      <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region:             <%= ENV['AWS_REGION'] %>
```

### Worker

```ruby
class ReportSubmitterWorker < ApplicationJob
  include Shoryuken::Worker
  shoryuken_options queue: 'development_reports', auto_delete: true

  def perform(account_id, report_type, start_date, end_date)
    account = Account.where(id: account_id).first
    begin
      ReportBringer.new(account).take_first_reports(report_type, start_date, end_date)
    rescue Excon::Error::ServiceUnavailable => error
      p error.response.message
    end
  end
end
```

### Call 

```ruby
 ReportSubmitterWorker.set(wait_until: Time.now + 1.minute).perform_later(@account.id, report_info[:type], start_date, end_date)
```

Please advice
