### ISSUE TITLE
Delay cannot be set per processing group

### ISSUE THREAD

**Issue by vvondra** [phstc/shoryuken#454]
The delay will be ignored in this case
```
groups:
  group_a:
    delay: 10
    queues:
      - queue_a
```

The global delay of 5s will be used in this case:
```
delay: 5
groups:
  group_a:
    delay: 10
    queues:
      - queue_a
```
  

:pushpin: #543
