### ISSUE TITLE
Local SQS with moto can't find queues

### ISSUE THREAD

**Issue by gbxl** [phstc/shoryuken#466]
I'm using straight moto server (`moto_server sqs -p 4576`) and with a `shoryuken.yml` like
```
aws:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV['AWS_REGION'] %>
concurrency: <%= ENV['WORKER_CONCURRENCY'] || 10 %>
endpoint: http://localhost:4576
verify_checksums: false
queues:
  - [<%= ENV['RAILS_ENV'] %>_urgent_priority, 10]
  - [<%= ENV['RAILS_ENV'] %>_high_priority, 6]
  - [<%= ENV['RAILS_ENV'] %>_medium_priority, 2]
  - [<%= ENV['RAILS_ENV'] %>_low_priority, 1]
```
I cannot get shoryuken to find the queues. If I run a curl agains't my localhost I do get the queues
```
➜  ~ curl -X POST http://localhost:4576/\?Action\=ListQueues
<ListQueuesResponse>
    <ListQueuesResult>
            <QueueUrl>http://localhost:4576/123456789012/development_high_priority</QueueUrl>
            <QueueUrl>http://localhost:4576/123456789012/development_medium_priority</QueueUrl>
            <QueueUrl>http://localhost:4576/123456789012/development_low_priority</QueueUrl>
    </ListQueuesResult>
    <ResponseMetadata>
        <RequestId></RequestId>
    </ResponseMetadata>
</ListQueuesResponse>
```
But wether it's within rails or just by running: `RAILS_ENV=development bundle exec shoryuken -R -C config/shoryuken.yml` I get:
```
bundler: failed to load command: shoryuken (/Users/lucasg/work/hollar/.bundle/ruby/2.3.0/bin/shoryuken)
ArgumentError: The specified queue(s) development_urgent_priority, development_high_priority, development_medium_priority, development_low_priority do not exist.
```

PS: using `aws-sdk (2.10.123)` and a fresh moto install

Any clue?
