### ISSUE TITLE
Long Polling

### ISSUE THREAD

**Issue by robert-carroll** [phstc/shoryuken#525]
Not really a bug, just missing a step.
Not sure how to set this up for long polling. When I create config/initializers/shoryuken.rb with
`Shoryuken.sqs_client_receive_message_opts = { wait_time_seconds: 20 }`

It doesn't seem to load or change the polling.
Guess I'm missing where to load the config file or how to include it in the worker.

**Comment by phstc** [comment]
Hi @robert-carroll 

Is your `config/initializers/shoryuken.rb` being loaded? `initializers` are loaded automatically only if you `--rails`.

**Comment by robert-carroll** [comment]
The config is not being loaded. How can I load it manually without rails?

**Comment by phstc** [comment]
@robert-carroll how are you starting shoryuken? You could `-r ./workers.rb`

```ruby
# workers.rb

Shoryuken.sqs_client_receive_message_opts = { wait_time_seconds: 20 }
# or
# require 'config/initializers/shoryuken.rb'

require 'my_worker_a.rb'
require 'my_worker_b.rb'
require 'my_worker_c.rb'
```

**Comment by phstc** [comment]
@robert-carroll I've just updated the long polling wiki adding these instructions ☝️, could you review it https://github.com/phstc/shoryuken/wiki/Long-Polling to check it? Feel free to update it 🍻

**Comment by robert-carroll** [comment]
```ruby
# fetch.rb
require './workers/events'
require './config/initializers/shoryuken'
```
before or after `require ./workers/events` returns

`$ bundle exec shoryuken -r ./fetch.rb -C shoryuken.yml`
undefined method `sqs_client_receive_message_opts=' for Shoryuken:Module

**Comment by robert-carroll** [comment]
```ruby
# fetch.rb
require 'shoryuken'
require './config/initializers/shoryuken'
require './workers/live_events'
```

same undefined method

**Comment by phstc** [comment]
That's very strange, because it is defined [here](https://github.com/phstc/shoryuken/blob/bc7938942270a1171d1597064698d88c3f36a4ec/lib/shoryuken.rb#L66).

What's the Shoryuken version you are using?

**Comment by robert-carroll** [comment]
Using shoryuken 2.0.2 w/ ruby 2.5.1p57

**Comment by phstc** [comment]
For 2.0.2 you need to configure it differently: https://github.com/phstc/shoryuken/tree/v2.0.2#configuration

```yaml
aws:
  access_key_id:      ...       # or <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key:  ...       # or <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region:             us-east-1 # or <%= ENV['AWS_REGION'] %>
  receive_message:              # See http://docs.aws.amazon.com/sdkforruby/api/Aws/SQS/Client.html#receive_message-instance_method
    # wait_time_seconds: N      # The number of seconds to wait for new messages when polling. Defaults to the #wait_time_seconds defined on the queue
```
