### ISSUE TITLE
Add ability to specify production and development in shoryuken.yml

### ISSUE THREAD

**Issue by spadachris** [phstc/shoryuken#559]
Currently I have two separate config files `shoryuken.yml` and `shoryuken.development.yml` which I pass in to `-C` based on the environment I am using.

It would be nice if I could just specify the configs based on the environment it is run in. 

For example:
```
prod:
  groups:
    group_name:
      concurrency: 5
      queues:
        - production-queue-name
development:
  groups:  
    group_name:
      concurrency: 5
      queues:
        - development-queue-name
```
