### ISSUE TITLE
Dynamically set configuration for local and production

### ISSUE THREAD

**Issue by truongnmt** [phstc/shoryuken#610]
My use case is to use Shoryuken as Ruby application, the worker is plain Ruby not using ActiveJob, no Rails initializer is run, I need a way to dynamically set endpoint and other settings by either env or using a different config file. In development, we want to use Mock SQS, while in production we use AWS.

```bash
bundle exec shoryuken --config config/shoryuken/local.yml
```
```yml
# config/shoryuken/local.yml
aws:
  access_key_id: 'sample key id'
  secret_access_key: 'sample access key'
  region: <%= ENV['AWS_REGION'] %>
  endpoint: ENV['LOCAL_DOCKER_AWS_SQS_ENDPOINT'] || 'http://localhost:9324'
  verify_checksums: false
concurrency: 20
require: ./app/workers
queues:
  - test-queue
```

```bash
bundle exec shoryuken --config config/shoryuken/production.yml
```
```yml
# config/shoryuken/production.yml
aws:
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
concurrency: 20
require: ./app/workers
queues:
  - test-queue
```

On reading about Shoryuken [running options](https://github.com/phstc/shoryuken/wiki/Shoryuken-options), I didn't see the options to specify AWS credential or endpoint in config file.

---

There is another way that is to configure_client and configure_server in worker:

```ruby
class MyWorker
  include Shoryuken::Worker
  shoryuken_options queue: 'test-queue', auto_delete: true

  # TODO: setting only if ENV is development
  Shoryuken.configure_client do |config|
    config.sqs_client = Aws::SQS::Client.new(
      region: ENV['AWS_REGION'],
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      endpoint: ENV['LOCAL_DOCKER_AWS_SQS_ENDPOINT'] || 'http://localhost:9324',
      verify_checksums: false
    )
  end
  Shoryuken.configure_server do |config|
    config.sqs_client = Aws::SQS::Client.new(
      region: ENV['AWS_REGION'],
      access_key_id: ENV['AWS_ACCESS_KEY_ID'],
      secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
      endpoint: ENV['LOCAL_DOCKER_AWS_SQS_ENDPOINT'] || 'http://localhost:9324',
      verify_checksums: false
    )
  end

  def perform(sqs_msg, body)
     ...
  end
end
```
